# Build stage
FROM node:20.12.0-slim
WORKDIR /app
COPY package*.json ./
ENV NODE_OPTIONS=--max_old_space_size=8192
RUN npm install
COPY . .
EXPOSE 3000 3978
CMD [ "/bin/sh", "-c", "npm run local-db:migrate && npm run start:product" ]